### ISSUE TITLE
Connect backend to the database

### ISSUE THREAD

**Issue by FelipeLFirmino** [FelipeLFirmino/Backend_youStore#6]
-  Connect the backend to the database and test if the data fetched is correct
-  Database: 
-

**Comment by bruno-sandes** [comment]
![Captura de tela 2024-05-23 235958](https://github.com/FelipeLFirmino/Backend_youStore/assets/102196535/6c020d2c-9fc6-4672-9637-343a43f9a0d0)
![Captura de tela 2024-05-23 235847](https://github.com/FelipeLFirmino/Backend_youStore/assets/102196535/25371285-2809-47b1-89c5-8cfe0e923d51)
![Captura de tela 2024-05-23 234432](https://github.com/FelipeLFirmino/Backend_youStore/assets/102196535/d5aab101-14bf-4e55-9f5e-8a8a44d5c2d2)
![Captura de tela 2024-05-23 235508](https://github.com/FelipeLFirmino/Backend_youStore/assets/102196535/52198215-effd-4a41-aa4d-f85828dbf94c)
